export const TimecodeFormat = {
  FRAMECOUNT: 'FRAMECOUNT',
  SECONDS: 'SECONDS',
  DROPFRAME: 'DROPFRAME',
  NONDROPFRAME: 'NONDROPFRAME',
  SIMPLE_TIME_CONVERSION: 'SIMPLE_TIME_CONVERSION',
  MINIMAL_TIME_CONVERSION: 'MINIMAL_TIME_CONVERSION'
};
